export const APP_FEATURES = [
  {
    id: "1",
    title: "Tailored Just for You",
    description:
      "Get interview questions and model answers based on your role, experience, and specific focus areas — no more generic prep.",
  },
  {
    id: "2",
    title: "Learn at Your Own Pace",
    description:
      "Expand answers only when you're ready. Dive deeper into any concept instantly with AI-powered detailed explanations.",
  },
  {
    id: "3",
    title: "Capture Your Insights",
    description:
      "Add personal notes to any question and pin important ones to the top — making your learning more organized and personal.",
  },
  {
    id: "4",
    title: 'Understand the "Why" Behind Answers',
    description:
      "Beyond just answers — unlock detailed concept explanations generated by AI, helping you truly master each topic.",
  },
  {
    id: "5",
    title: "Save, Organize, and Revisit",
    description:
      "Easily save your interview sets, organize them neatly in your dashboard, and pick up your preparation right where you left off.",
  },
];
